# GENERATED FILE — do not edit manually.
# Auto-generated by scripts/codegen/gen_shared_schemas.py
# Single source of truth: packages/shared/src/schemas/document.ts
# Re-run codegen after modifying TEMPLATE_META_RESERVED_KEYS.

from __future__ import annotations

__all__ = ["TEMPLATE_META_RESERVED_KEYS"]

# frozenset so the backend can cheaply copy and freeze.
TEMPLATE_META_RESERVED_KEYS: frozenset[str] = frozenset([
    "id", "version", "layer", "matched_type", "confidence", "reason"
])
