CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS metaedu;

ALTER DEFAULT PRIVILEGES IN SCHEMA metaedu GRANT ALL ON TABLES TO metaedu;
ALTER DEFAULT PRIVILEGES IN SCHEMA metaedu GRANT ALL ON SEQUENCES TO metaedu;
