#!/usr/bin/env python3
"""
Codegen: extract TEMPLATE_META_RESERVED_KEYS from @metaedu/shared TypeScript source
and emit a Python frozenset so the backend can import it as a single source of truth.

Run:
    python scripts/codegen/gen_shared_schemas.py

Or via pnpm (from repo root):
    pnpm --filter @metaedu/shared codegen

Integrates with:
- CI: `check-engineering-docs` gate fails if generated file is stale.
- Pre-commit: add to pre-commit hook after `pnpm install`.

Single source of truth: packages/shared/src/schemas/document.ts
Generated artifact:  packages/server-python/app/shared/schemas/document.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
TS_SOURCE = REPO_ROOT / "packages/shared/src/schemas/document.ts"
PY_TARGET = REPO_ROOT / "packages/server-python/app/shared/schemas/document.py"
PY_INIT = REPO_ROOT / "packages/server-python/app/shared/schemas/__init__.py"


def extract_keys_from_ts(ts_content: str) -> list[str]:
    """Extract TEMPLATE_META_RESERVED_KEYS string values from document.ts."""
    # Match the whole `new Set([...])` with balanced bracket counting.
    # Finds: export const TEMPLATE_META_RESERVED_KEYS: ReadonlySet<string> = new Set([...]);
    pattern = (
        r"export\s+const\s+TEMPLATE_META_RESERVED_KEYS"
        r"\s*:\s*ReadonlySet<string>"
        r"\s*=\s*new\s+Set\(\s*"
    )
    m = re.search(pattern, ts_content)
    if not m:
        raise ValueError(
            "TEMPLATE_META_RESERVED_KEYS not found in document.ts. "
            "Make sure the constant is exported and matches the expected pattern."
        )
    start = m.end()
    # Walk from 'start' counting brackets to find the matching ']'
    depth = 0
    i = start
    while i < len(ts_content):
        ch = ts_content[i]
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                break
        i += 1
    inner = ts_content[start:i]
    # Extract string literals (handles both single and double quotes)
    strings = re.findall(r'''["']([^"']+)["']''', inner)
    if not strings:
        raise ValueError(f"No string keys found inside TEMPLATE_META_RESERVED_KEYS Set: {inner!r}")
    return strings


def build_python_file(keys: list[str]) -> str:
    """Build the generated Python module content."""
    key_reprs = ", ".join(f'"{k}"' for k in keys)
    return (
        "# GENERATED FILE — do not edit manually.\n"
        "# Auto-generated by scripts/codegen/gen_shared_schemas.py\n"
        "# Single source of truth: packages/shared/src/schemas/document.ts\n"
        "# Re-run codegen after modifying TEMPLATE_META_RESERVED_KEYS.\n"
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "__all__ = [\"TEMPLATE_META_RESERVED_KEYS\"]\n"
        "\n"
        "# frozenset so the backend can cheaply copy and freeze.\n"
        "TEMPLATE_META_RESERVED_KEYS: frozenset[str] = frozenset([\n"
        f"    {key_reprs}\n"
        "])\n"
    )


def main(argv: list[str] | None = None) -> int:
    if len(argv) > 1:
        print(f"Usage: {argv[0]}")
        print("  Regenerates packages/server-python/app/shared/schemas/document.py")
        return 0

    ts_content = TS_SOURCE.read_text(encoding="utf-8")
    keys = extract_keys_from_ts(ts_content)
    py_content = build_python_file(keys)

    # Ensure target directory exists
    PY_TARGET.parent.mkdir(parents=True, exist_ok=True)

    # Write only if content changed (avoid spurious re-runs)
    if PY_TARGET.exists() and PY_TARGET.read_text(encoding="utf-8") == py_content:
        print(f"Already up to date: {PY_TARGET}")
        return 0

    PY_TARGET.write_text(py_content, encoding="utf-8")
    print(f"Generated: {PY_TARGET} ({len(keys)} keys)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
